package jdbcgui;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wissam
 */
public class OrganizeEvent extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;
    LoginUser luser;

    public OrganizeEvent(LoginUser user) {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblProfIDError.setVisible(false);
        lblEventIDError.setVisible(false);
        dbCon = new myDBCon();

        luser = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtProfID = new javax.swing.JTextField();
        txtEventID = new javax.swing.JTextField();
        btnAddNewEmp = new javax.swing.JButton();
        lblProfIDError = new javax.swing.JLabel();
        lblEventIDError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Organize Event");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Organize Event");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PROFID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("EVENTID:");

        txtProfID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtEventID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAddNewEmp.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewEmp.setText("Add New");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        lblProfIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblProfIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblProfIDError.setText("error label");

        lblEventIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblEventIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblEventIDError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProfID)
                            .addComponent(txtEventID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddNewEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblProfIDError, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(lblEventIDError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEventID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEventIDError))
                .addGap(20, 20, 20)
                .addComponent(btnAddNewEmp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblProfIDError.setText("");
        lblProfIDError.setVisible(false);
        lblEventIDError.setText("");
        lblEventIDError.setVisible(false);
    }

    private void setErrorMessage(JLabel label, String text) {
        label.setText(text);
        label.setVisible(true);
    }
    
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        try {
            if (txtProfID.getText().trim().isEmpty()) {
                setErrorMessage(lblProfIDError, "Required.");
                result = false;
            } else if (!isInteger(txtProfID.getText().trim())) {
                setErrorMessage(lblProfIDError, "Must be integer.");
                result = false;
            } else if (!isProfessor()) {
                throw new Exception();
            }
        } catch (Exception e) {
            setErrorMessage(lblProfIDError, "Invalid professor ID.");
            result = false;
        }

        try {
            if (txtEventID.getText().trim().isEmpty()) {
                setErrorMessage(lblEventIDError, "Required.");
                result = false;
            } else if (!isInteger(txtEventID.getText().trim())) {
                setErrorMessage(lblEventIDError, "Must be integer.");
                result = false;
            } else if (!isValidEventID()) {
                throw new Exception();
            }
        } catch (Exception e) {
            setErrorMessage(lblEventIDError, "Invalid event ID.");
            result = false;
        }

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        txtProfID.setText("");
        txtEventID.setText("");
    }

    boolean isValidEventID() throws SQLException {
        String stmtSQL = "SELECT eventID FROM event WHERE eventID = " + txtEventID.getText().trim();
        rs = dbCon.executeStatement(stmtSQL);
        return rs.isBeforeFirst();
    }

    boolean isProfessor() throws SQLException {
        String stmtSQL = "SELECT profID FROM professor WHERE profID = " + txtProfID.getText().trim();
        rs = dbCon.executeStatement(stmtSQL);
        return rs.isBeforeFirst();
    }

    boolean isDuplicate(String profID, String eventID) throws SQLException {
        String stmtSQL = "SELECT profID, eventID FROM organize WHERE profID = " + profID + " AND eventID = " + eventID;
        rs = dbCon.executeStatement(stmtSQL);
        return rs.isBeforeFirst();
    }

    void updateLogs(String action) {
        try {
            String prepSQL = "INSERT INTO log VALUES (?,?,?,SYSTIMESTAMP)";
            PreparedStatement preparedStatement = dbCon.prepareStatement(prepSQL);
            preparedStatement.setInt(1, luser.userid);
            preparedStatement.setString(2, luser.username);
            preparedStatement.setString(3, action);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error inserting the logs.");
        }
    }

    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        
        try {

            if (isValidData() && !isDuplicate(txtProfID.getText().trim(), txtEventID.getText().trim())) {

                String prepSQL = "INSERT INTO organize (profID, eventID) VALUES (?, ?)";
                PreparedStatement preparedStatement = dbCon.prepareStatement(prepSQL);
                preparedStatement.setInt(1, Integer.parseInt(txtProfID.getText().trim()));
                preparedStatement.setInt(2, Integer.parseInt(txtEventID.getText().trim()));

                int result = preparedStatement.executeUpdate();

                if (result > 0) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Event has been organized added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                    String action = "ProfID " + txtProfID.getText().trim() + " organized eventID " + txtEventID.getText().trim();
                    updateLogs(action);

                    clearInputBoxes();
                }

                rs.close();
            } else if (!isValidData()) {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Professor already organizes the Event.");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding a new organized event.");
        }
    }//GEN-LAST:event_btnAddNewEmpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblEventIDError;
    private javax.swing.JLabel lblProfIDError;
    private javax.swing.JTextField txtEventID;
    private javax.swing.JTextField txtProfID;
    // End of variables declaration//GEN-END:variables
}
